"""add language to posts

Revision ID: 627134486ba5
Revises: ab445bd02610
Create Date: 2020-05-31 20:11:50.967781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627134486ba5'
down_revision = 'ab445bd02610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
